/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#c8c6c7",
        "on-error-container": "#ffdad6",
        "surface-container-lowest": "#040e1f",
        "primary-fixed": "#ffe16d",
        "surface-tint": "#e9c400",
        "error-container": "#93000a",
        "on-secondary-fixed-variant": "#653e00",
        "secondary-fixed-dim": "#ffb95f",
        "on-tertiary-fixed": "#1c1b1c",
        "surface-variant": "#2a3548",
        "inverse-primary": "#705d00",
        "secondary": "#ffb95f",
        "background": "#081425",
        "outline-variant": "#4d4732",
        "outline": "#999077",
        "on-surface-variant": "#d0c6ab",
        "on-primary-fixed": "#221b00",
        "error": "#ffb4ab",
        "tertiary": "#f9f5f6",
        "surface-dim": "#081425",
        "primary-fixed-dim": "#e9c400",
        "surface": "#081425",
        "secondary-container": "#ee9800",
        "surface-container-high": "#1f2a3c",
        "surface-container": "#152031",
        "on-error": "#690005",
        "on-surface": "#d8e3fb",
        "on-primary-fixed-variant": "#544600",
        "on-primary": "#3a3000",
        "on-secondary-fixed": "#2a1700",
        "secondary-fixed": "#ffddb8",
        "on-tertiary-container": "#605e60",
        "on-tertiary": "#313031",
        "on-tertiary-fixed-variant": "#474647",
        "on-primary-container": "#705e00",
        "primary": "#fff6df",
        "on-background": "#d8e3fb",
        "inverse-on-surface": "#263143",
        "on-secondary": "#472a00",
        "on-secondary-container": "#5b3800",
        "inverse-surface": "#d8e3fb",
        "surface-bright": "#2f3a4c",
        "tertiary-container": "#dcd9da",
        "tertiary-fixed": "#e5e2e3",
        "primary-container": "#ffd700",
        "surface-container-highest": "#2a3548",
        "surface-container-low": "#111c2d"
      },
      borderRadius: {
        "DEFAULT": "0px",
        "sm": "0px",
        "md": "0px",
        "lg": "0px",
        "xl": "0px",
        "2xl": "0px",
        "3xl": "0px",
        "full": "0px"
      },
      spacing: {
        "container-max": "1440px",
        "unit": "8px",
        "margin-desktop": "64px",
        "margin-mobile": "20px",
        "gutter": "24px"
      },
      fontFamily: {
        "body-lg": ["var(--font-sora)", "sans-serif"],
        "headline-lg": ["var(--font-sora)", "sans-serif"],
        "body-md": ["var(--font-sora)", "sans-serif"],
        "headline-xl": ["var(--font-sora)", "sans-serif"],
        "label-bold": ["var(--font-sora)", "sans-serif"],
        "headline-md": ["var(--font-sora)", "sans-serif"],
        "label-sm": ["var(--font-sora)", "sans-serif"],
        "headline-lg-mobile": ["var(--font-sora)", "sans-serif"],
        "sora": ["var(--font-sora)", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["12px", {"lineHeight": "16px", "fontWeight": "400"}],
        "headline-lg": ["16px", {"lineHeight": "20px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "body-md": ["11px", {"lineHeight": "14px", "fontWeight": "400"}],
        "headline-xl": ["20px", {"lineHeight": "24px", "letterSpacing": "-0.02em", "fontWeight": "800"}],
        "label-bold": ["10px", {"lineHeight": "12px", "letterSpacing": "0.05em", "fontWeight": "700"}],
        "headline-md": ["14px", {"lineHeight": "18px", "fontWeight": "600"}],
        "label-sm": ["9px", {"lineHeight": "10px", "fontWeight": "500"}],
        "headline-lg-mobile": ["14px", {"lineHeight": "18px", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
};
